### ISSUE TITLE
Awards: Make laurels static

### ISSUE THREAD

**Issue by so-ale** [so-ale/cielo-thefilm#10]
> 11.	The Awards page has laurels at the bottom.They should be anchored like the laurels on the home page so people can see them on smaller screens. At the moment, you have to scroll down to see them.

One solution is to superimpose laurels to the background image.
Another solution is to give it a fixed positioning. Explore whichever solution works best for most devices. 

> 12.	I asked for a Photoshop file but they did not use Photoshop. They uploaded the TIF images all separately for the Awards page: Photo; texts; laurels.

**Comment by so-ale** [comment]
@alsionsites I have made some changes here: https://staging4.cielo-thefilm.com/about/awards/

I think it was better the way it was before. What do you think?

**Comment by alsionsites** [comment]
hi Sohail,

i liked it better as it was before. 

to clarify my request: can the laurels be fixed to the bottom of the page in the same way they are fixed to the bottom of the home page? this way every screen sees the laurels but they don’t interfere with the text. does that make sense? thank you

**Comment by so-ale** [comment]
The laurel badges work for the home screen because there is barely any text in it. Other screens where there is a lot of text will definitely interfere with the badges. 

Take the modified Awards page for example. What I've done is exactly what is done on the home page. It works for homepage because there is no text in it. And the same doesn't work for the awards page which has a lot of text. 

The only other page where they can be put is the contact page, as it has very little text. Let me know what you think.

**Comment by alsionsites** [comment]
Hi Sohail,

ok. then we can keep it as it was before. not important to try and fix the laurels. It does not work for me what you showed me

thanks

**Comment by so-ale** [comment]
Okay. Reverted back to the original Awards Page.

**Comment by alsionsites** [comment]
hi Sohail,

how is the site? when can you finish it? 
thanks.
