### ISSUE TITLE
Fix loading of website

### ISSUE THREAD

**Issue by so-ale** [so-ale/cielo-thefilm#11]
> Please fix the loading of the website. The pages load differently, some slowly, others faster. With some the text appears first. On the home page a black and white image of the trees appears before the colour image appears etc.

@alsionsites This is likely happening because heavier images take longer to load than light-weight text. 
I will try and look for a solution where all the content loads first before displaying together. This will give a felling of smooth loading.

**Comment by alsionsites** [comment]
great!
thank you

Alison McAlpine   
+1 514-882-4810 
cielo-thefilm.com <http://cielo-thefilm.com/>
alisonmcalpine.com <http://alisonmcalpine.com/>

**Comment by so-ale** [comment]
A preloader has been attached. Loading is much smoother now. Load time will be further reduced when data heavy background images are optimized.

**Comment by so-ale** [comment]
Time consumed: 00:45

(Image to be optimized at #12 )
