### ISSUE TITLE
Awards Pages-Text additions

### ISSUE THREAD

**Issue by alsionsites** [so-ale/cielo-thefilm#15]
[AWARDS page-Additions.docx](https://github.com/so-ale/cielo-thefilm/files/3025756/AWARDS.page-Additions.docx)

**Comment by so-ale** [comment]
Done.

Time consumed: 01:00 hours

**Comment by so-ale** [comment]
get rid of faint lines

**Comment by so-ale** [comment]
Removed the faint separator lines in between the texts.
